# _config.yml

navigation:
  - name: Projects
    link: /projects/
  - name: Posts
    link: /posts/
  - name: About
    link: /about/

collections:
  projects:
    output: true
    permalink: /projects/:path/
    defaults:
    - scope:
        path: "_projects"
        type: "projects"
      values:
        layout: "project"
        comments: true
        card_title: "Project Title"
        excerpt: "Project description"
        tech_stack: []
        github: ""
  posts:
    output: true
    permalink: /posts/:path/
    defaults:
      - scope:
          path: "_posts"
          type: "posts"
        values:
          layout: "post"
          comments: true

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: text
    span:
      line_numbers: false
    block:
      line_numbers: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock