navigation:
  - name: Projects
    link: /projects/
  - name: Posts
    link: /posts/
  - name: About
    link: /about/

projects:
  - title: AFT calculator
    url: /projects/flametemp
  - title: Chemical Compound Parser
    url: /projects/chemcount
  - title: Website
    url: /projects/website

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock