navigation:
  - name: Projects
    link: /projects/
  - name: Posts
    link: /posts/
  - name: About
    link: /about/

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
      comments: true
      card_title: "Project Title"
      excerpt: "Project description"
      tech_stack: []
      github: ""

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock