navigation:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Projects
    link: /projects/
  - name: Posts
    link: /posts/

projects:
  - title: AFT calculator
    url: /projects/flametemp
  - title: Chemical Counter
    url: /projects/chemcount
  - title: Website
    url: /projects/website

sass:
  sass_dir: css
  style: compressed